### ISSUE TITLE
Summary - Unable to continue missing dependencies

### ISSUE THREAD

**Issue by Tereseus** [istrong1/Jamming-Project#3]
Since package.json and spotify.js are missing I can no longer test your project. You are in fact not done with the project or have not submitted everything that is required. If there was some type of mistake be sure to resubmit your project or if you need help with the following steps feel free to reach out to the advisors who can help you finish the project. From what I can tell you did do something right though so you are on the correct path, now you just need to finish.

**Comment by istrong1** [comment]
Hey, sorry about that, I've added both hopefully
